# Use OpenJDK 21 slim image
FROM openjdk:21-slim
WORKDIR /app/backend

# Install git
RUN apt-get update && apt-get install -y git

# Clone backend repo
RUN git clone https://github.com/2300030174/cicd_project_backend.git .

# Make gradlew executable
RUN chmod +x ./gradlew

# Build the backend skipping tests
RUN ./gradlew build -x test

# Expose backend port
EXPOSE 5001

# Run the Spring Boot app
CMD ["java", "-jar", "build/libs/backend-0.0.1-SNAPSHOT.jar"]
