version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: home_services-db
    restart: always
    environment:
      MYSQL_DATABASE: home_services_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - home_services-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: home_services-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/home_services_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "5001:5001"   # matches server.port
    networks:
      - home_services-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: home_services-frontend
    restart: always
    environment:
      REACT_APP_BACKEND_URL: http://backend:5001   # optional: for React to know backend URL
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - home_services-net

volumes:
  db_data:

networks:
  home_services-net:
    driver: bridge
