# Use Gradle + OpenJDK image
FROM gradle:8.3-jdk21-alpine

WORKDIR /app

# Install git
RUN apk add --no-cache git

# Clone the backend repo
RUN git clone https://github.com/2300030174/cicd_project_backend.git .

# Build the project
RUN gradle build -x test

# Expose backend port
EXPOSE 5001

# Run the application
CMD ["java", "-jar", "build/libs/demo-0.0.1-SNAPSHOT.jar"]
