name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /home/ubuntu/ecommercefullstack

      - name: Deploy and Debug on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          debug: true
          script: |
            cd /home/ubuntu/ecommercefullstack
            
            # Stop any existing containers
            sudo docker compose down || true
            
            # Build and start
            sudo docker compose up -d --build
            
            # Wait for services
            sleep 30
            
            # Debug info
            echo "=== CONTAINER STATUS ==="
            sudo docker compose ps
            
            echo "=== BACKEND LOGS ==="
            sudo docker compose logs backend --tail=50
            
            echo "=== FRONTEND LOGS ==="  
            sudo docker compose logs frontend --tail=50
            
            echo "=== TEST BACKEND DIRECTLY ==="
            curl -v http://localhost:5001/api/health || echo "Backend direct test failed"
            
            echo "=== TEST VIA NGINX ==="
            curl -v http://localhost/api/health || echo "Nginx proxy test failed"
