name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/ecommercefullstack
            
            # Stop existing containers
            sudo docker-compose down || true
            
            # Pull latest code
            git pull origin main || true
            
            # Deploy
            sudo docker-compose up -d --build
            
            # Wait and check status
            sleep 30
            sudo docker-compose ps
            sudo docker-compose logs backend --tail=20
